# -*- coding: utf-8 -*-
from . import pabs_eleanor_area
from . import pabs_eleanor_disease
from . import stock_warehouse
from . import hr_department
from . import hr_job
from . import hr_employee
from . import pabs_eleanor_status_log
from . import pabs_eleanor_inability
from . import res_users
from . import pabs_eleanor_user_access
from . import pabs_eleanor_concept_category
from . import pabs_eleanor_concept
from . import pabs_eleanor_period
from . import pabs_eleanor_move
from . import pabs_eleanor_move_binnacle
from . import pabs_eleanor_salary_history
from . import pabs_eleanor_taxpayer
from . import pabs_eleanor_ema
from . import pabs_eleanor_eba
from . import pabs_eleanor_migration
from . import pabs_eleanor_job_category