# -*- coding: utf-8 -*-
{
  'name' : 'Customizacion PABS',
  'summary': 'Coded By: Eduardo Serrano(eduardo.serrano@pabsmr.org)',
  'author' : 'PABS',
  'category': 'Custom',
  'website': 'https://www.pabsmr.org',
  'depends' : [
    'base', 
    'stock',
    'sale_management',
    'account_accountant',
    'account',
    'product',
    'purchase',
    'stock_account',
    'contacts',
    'hr'],
  'data': [
    'data/ir_sequence.xml',
    'data/data.xml',
    'security/groups.xml',
    'reports/closing_transfer_report.xml',
    'reports/pabs_econtract_closing_transfer_report.xml',
    'reports/arching_report.xml',
    'views/res_company_view.xml',
    'views/pabs_office_view.xml',
    'views/hr_employee_view.xml',
    'views/payment_scheme_view.xml',
    'views/recluitment_origin_view.xml',
    'views/recluitment_induction_view.xml',
    'views/pabs_contract_comments_view.xml',
    'views/contract_view.xml',
    'views/product_pricelist_view.xml',
    'views/stock_location_view.xml',
    'views/stock_picking_view.xml',
    'views/stock_production_lot_view.xml',
    'views/purchase_order_view.xml',
    'views/closing_transfer_view.xml',
    'views/account_move_view.xml',
    'views/res_locality.xml',
    'views/colonias.xml',
    'views/pabs_comission_template_of_templates_view.xml',
    'views/pabs_comission_template_view.xml',
    'views/pabs_comission_tree_view.xml',
    'views/pabs_comission_debt_collector.xml',
    'views/pabs_comission_output.xml',
    'views/account_payment_view.xml',
    'views/pabs_bonus_view.xml',
    'views/pabs_bonus_as_view.xml',
    'views/pabs_bonus_log_view.xml',
    'views/assets.xml',
    'wizard/pabs_status_stock_view.xml',
    'views/pabs_contract_status_view.xml',
    'views/pabs_contract_status_reason_view.xml',
    'views/res_config_settings_view.xml',
    'views/product_category_view.xml',
    'views/product_template_view.xml',
    'wizard/pabs_closing_transfer_wizard_view.xml',
    'wizard/fix_stock_move_wizard_view.xml',
    'wizard/pabs_single_contract_wizard_view.xml',
    'wizard/pabs_arching_view.xml',
    'wizard/output_payment_wizard_view.xml',
    'wizard/pabs_econtract_closing_transfer_wizard.xml',
    'wizard/pabs_econtract_wizard_view.xml',
    'wizard/add_balance_wizard_view.xml',
    'wizard/show_digital_images_wizard_view.xml',
    'security/security.xml',
    'security/groups.xml',
    'views/menu_views.xml',
    'security/ir.model.access.csv',
    ],
  'installable': True,
  'auto_install': False,
}
