# -*- coding: utf-8 -*-
{
  'name' : 'REPORTES PABS',
  'summary': 'Coded By: Luis (luis.lopez@pabsmr.org)',
  'author' : 'PABS',
  'category': 'Reports',
  'website': 'https://www.pabsmr.org',
  'depends' : [
    'xmarts_funeraria',
    'mortuary',
    'report_xlsx',
    'stock',
    'pabs_custom'],
  'data': [
    'security/security.xml',
    'security/ir.model.access.csv',
    'wizard/production_contract.xml',
    'wizard/pabs_daily_helps_wizard.xml',
    'wizard/pabs_acumulated_report_wizard.xml',
    'wizard/pabs_daily_helps_wizard.xml',
    'wizard/pabs_collector_report_wizard.xml',
    'wizard/report_pabs_ing_egre_wizard.xml',
    'wizard/transfer_portfolio_partners_wizard.xml',
    'wizard/delinquent_customer_wizard.xml',
    'wizard/pabs_debt_collector_wizard.xml',
    'wizard/pabs_stock_push_and_pull_wizard_view.xml',
    'wizard/pabs_contratos_pagados_wizard.xml',
    'reports/elaborated_contracts.xml',
    'reports/pabs_collector_report_template.xml',
    'reports/delinquent_customer_template.xml',
    'reports/commissions_to_recovery_template.xml',
    'reports/pabs_debt_collector_template.xml',
    'reports/mortuary_product_invoiced_template.xml',
    'reports/accounting_policy_template.xml',
    'wizard/pabs_commissions_recovery_wizard.xml',
    'wizard/pabs_contracts_done_wizard.xml',
    'wizard/mortuary_product_invoiced_wizard.xml',
    'wizard/pabs_verification_wizard.xml',
    'wizard/pabs_difference_between_amount_contracts_wizard_view.xml',
    'wizard/pabs_commissions_as_wizard.xml',
    'views/stock_quant_view.xml',
    'views/account_move_view.xml',
    'views/menus.xml',
    
    ],
  'installable': True,
  'auto_install': False,
}